### ISSUE TITLE
Variables....

### ISSUE THREAD

**Issue by dishapatel010** [Imyr/TeleRG#2]
Can u give example/ explanation for  [config](https://github.com/Imyr/TeleRG/blob/c129cdf2475a274e2c0a872aad457bb35a85c06c/config.json) stuff

**Comment by Imyr** [comment]
**id**: Telegram Group ID (_-1001231231231_)
**url**: link to RSS (_https://timesofindia.indiatimes.com/rssfeedstopstories.cms_)
**command**: Bot mirror command (_/mirror@mirrorbot_)
**incl** [Optional]: will only download files that have any of the following strings in their title  (_["1080p", "2021"]_)
**excl** [Optional]: will not download files that have any of the following strings in their title  (_["VXT", "HDTV", "ION10"]_)

**Comment by dishapatel010** [comment]
> **id**: Telegram Group ID (_-1001231231231_)
> **url**: link to RSS (_https://timesofindia.indiatimes.com/rssfeedstopstories.cms_)
> **command**: Bot mirror command (_/mirror@mirrorbot_)
> **incl** [Optional]: will only download files that have any of the following strings in their title (_["1080p", "2021"]_)
> **excl** [Optional]: will not download files that have any of the following strings in their title (_["VXT", "HDTV", "ION10"]_)

Where will be bot token ?  & also explain [credentials.json](https://github.com/Imyr/TeleRG/blob/c129cdf2475a274e2c0a872aad457bb35a85c06c/credentials.json)

**Comment by Imyr** [comment]
**log**: log channel/group id (_-1002313212311_)
**tg_id**: telegram api id (_1123129_)
**tg_hash**: telegram api hash (_"abcbab123971bababavasdasd"_)
**mongodb_url**: mongodb database url with password (_mongodb+srv://user:pass@url.com/tablename?retryWrites=true&w=majority_)

It uses one's accounts session (can call it a userbot, maybe), so bot token isn't needed.
Also, the first time it's run, it asks for your login credentials. That is to generate the mentioned .session file (I don't know the exact terminology). So, it's recommended to run locally first to generate said file.
I don't know how to work with user session strings (which might eliminate the need for the session file, hence making the process a lot easier).
Any help or links to documentation/resources is appreciated.
